//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillInstance
    {
        public SkillInstance()
        {
            this.SkillReferences = new HashSet<SkillReference>();
            this.SkillReferences1 = new HashSet<SkillReference>();
            this.SkillReferences2 = new HashSet<SkillReference>();
            this.SkillReferences3 = new HashSet<SkillReference>();
            this.SkillReferences4 = new HashSet<SkillReference>();
            this.SkillReferences5 = new HashSet<SkillReference>();
            this.SkillReferences6 = new HashSet<SkillReference>();
            this.SkillReferences7 = new HashSet<SkillReference>();
            this.SkillReferences8 = new HashSet<SkillReference>();
            this.SkillReferences9 = new HashSet<SkillReference>();
            this.SkillReferences10 = new HashSet<SkillReference>();
            this.SkillReferences11 = new HashSet<SkillReference>();
            this.SkillReferences12 = new HashSet<SkillReference>();
            this.SkillReferences13 = new HashSet<SkillReference>();
            this.SkillReferences14 = new HashSet<SkillReference>();
            this.SkillReferences15 = new HashSet<SkillReference>();
            this.SkillReferences16 = new HashSet<SkillReference>();
            this.SkillReferences17 = new HashSet<SkillReference>();
            this.SkillReferences18 = new HashSet<SkillReference>();
            this.SkillReferences19 = new HashSet<SkillReference>();
            this.SkillReferences20 = new HashSet<SkillReference>();
        }
    
        public int SkillId { get; set; }
        public int CategoryId { get; set; }
        public string SkillName { get; set; }
        public string SkillString { get; set; }
        public int SkillNormallized { get; set; }
        public double SkillStringValue { get; set; }
        public string SkillNameVietnam { get; set; }
    
        public virtual SkillCategory SkillCategory { get; set; }
        public virtual ICollection<SkillReference> SkillReferences { get; set; }
        public virtual ICollection<SkillReference> SkillReferences1 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences2 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences3 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences4 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences5 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences6 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences7 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences8 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences9 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences10 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences11 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences12 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences13 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences14 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences15 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences16 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences17 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences18 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences19 { get; set; }
        public virtual ICollection<SkillReference> SkillReferences20 { get; set; }
    }
}
