//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MS_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int AccountId { get; set; }
        [Display(Name = "Username")]
        [Required(ErrorMessage = "Xin vui lòng nhập tên đăng nhập")]
        public string Username { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Xin vui lòng nhập mật khẩu")]
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string Role { get; set; }
        public bool IsWebmaster { get; set; }
        public string Avatar { get; set; }
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Định dạng email không đúng")]
        public string Email { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MaidMediator MaidMediator { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
