//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int CustomerId { get; set; }
        public int JobRequestId { get; set; }
        public System.DateTime PostTime { get; set; }
        public string CommentContent { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual JobRequest JobRequest { get; set; }
    }
}
