//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifier
    {
        public int Id { get; set; }
        public int AccId { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
        public string Link { get; set; }
        public bool View { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
