//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillCategory
    {
        public SkillCategory()
        {
            this.SkillInstances = new HashSet<SkillInstance>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<SkillInstance> SkillInstances { get; set; }
    }
}
