//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        public JobRequest()
        {
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.Recruitments = new HashSet<Recruitment>();
        }
    
        public int JobRequestId { get; set; }
        public int SkillRefId { get; set; }
        public Nullable<int> MaidMediatorId { get; set; }
        public int Status { get; set; }
        public System.DateTime PostTime { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Maid Maid { get; set; }
        public virtual MaidMediator MaidMediator { get; set; }
        public virtual SkillReference SkillReference { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Recruitment> Recruitments { get; set; }
    }
}
