//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaidMediator
    {
        public MaidMediator()
        {
            this.JobRequests = new HashSet<JobRequest>();
            this.Maids = new HashSet<Maid>();
        }
    
        public int AccountId { get; set; }
        public Nullable<int> ApplyTimes { get; set; }
        public double Payment { get; set; }
        public int MaidId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<JobRequest> JobRequests { get; set; }
        public virtual ICollection<Maid> Maids { get; set; }
    }
}
