//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSEntities : DbContext
    {
        public MSEntities()
            : base("name=MSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Apply> Applies { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<JobRequest> JobRequests { get; set; }
        public DbSet<Maid> Maids { get; set; }
        public DbSet<MaidMediator> MaidMediators { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Recruitment> Recruitments { get; set; }
        public DbSet<SkillCategory> SkillCategories { get; set; }
        public DbSet<SkillInstance> SkillInstances { get; set; }
        public DbSet<SkillReference> SkillReferences { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
