//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillReference
    {
        public SkillReference()
        {
            this.JobRequests = new HashSet<JobRequest>();
            this.Recruitments = new HashSet<Recruitment>();
        }
    
        public int SkillRefId { get; set; }
        public int Gender { get; set; }
        public int Cooking { get; set; }
        public int Babysister { get; set; }
    
        public virtual ICollection<JobRequest> JobRequests { get; set; }
        public virtual ICollection<Recruitment> Recruitments { get; set; }
        public virtual SkillInstance SkillInstance { get; set; }
    }
}
