//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillInstance
    {
        public SkillInstance()
        {
            this.SkillReferences = new HashSet<SkillReference>();
        }
    
        public int SkillId { get; set; }
        public int CategoryId { get; set; }
        public string SkillName { get; set; }
        public string SkillString { get; set; }
        public int SkillNormallized { get; set; }
        public double SkillStringValue { get; set; }
        public string SkillNameVietnam { get; set; }
    
        public virtual SkillCategory SkillCategory { get; set; }
        public virtual ICollection<SkillReference> SkillReferences { get; set; }
    }
}
